
language: python
python:
- '2.7'
- '3.4'
# copied from nolearn
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
install:
- pip install -r requirements.txt
- python setup.py develop
- travis_wait 60 pyensembl install --release 75 --species human
- travis_wait 60 pyensembl install --release 77 --species human
- travis_wait 60 pyensembl install --release 79 --species human
- travis_wait 60 pyensembl install --release 81 --species human
- travis_wait 60 pyensembl install --release 81 --species mouse
script: nosetests test && ./lint.sh
deploy:
  provider: pypi
  user: hammerlab
  password:
    secure: gJSWl4PLXKtVc2ERwbzfd4qKk9Yy4T8dpfR7Q89VLVXTd7Tv1SsEknShJZUFaCPN85aYFcAWsoOI6vSlBSdXeTONU/pmPgcWOLfiErsgCqUs6qq7edOhrtOS307SREX4oF6AF2iyJduWAF4NPq+9IoJUROIiB4u5qeUtWfVu2Eo=
  on:
    tags: true
